-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for Fintech Lending & Payments Analytics
-- Indonesian P2P lending and digital payments platform analytics
-- ============================================================================
USE DATABASE DIGITAL_FINTECH;
USE SCHEMA RAW;

-- 200K registered borrowers across Indonesia
CREATE OR REPLACE TABLE RAW.BORROWERS (
  BORROWER_ID VARCHAR(20) NOT NULL, PROVINCE VARCHAR(50), CITY VARCHAR(50), AGE_GROUP VARCHAR(20), EMPLOYMENT_TYPE VARCHAR(30), MONTHLY_INCOME FLOAT, CREDIT_SCORE INT, KTP_VERIFIED BOOLEAN, REGISTRATION_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 500K loans disbursed over 12 months
CREATE OR REPLACE TABLE RAW.LOANS (
  LOAN_ID VARCHAR(30) NOT NULL, BORROWER_ID VARCHAR(20), LOAN_AMOUNT FLOAT, INTEREST_RATE FLOAT, TENOR_DAYS INT, DISBURSEMENT_DATE DATE, DUE_DATE DATE, REPAID_DATE DATE, STATUS VARCHAR(20), PRODUCT_TYPE VARCHAR(30), RISK_GRADE VARCHAR(5), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Digital payment transactions
CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
  TXN_ID VARCHAR(30) NOT NULL, BORROWER_ID VARCHAR(20), TXN_TYPE VARCHAR(20), AMOUNT FLOAT, CHANNEL VARCHAR(30), TXN_DATE TIMESTAMP, MERCHANT_CATEGORY VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Collection activities for overdue loans
CREATE OR REPLACE TABLE RAW.COLLECTIONS (
  COLLECTION_ID VARCHAR(30) NOT NULL, LOAN_ID VARCHAR(30), ACTION_DATE DATE, ACTION_TYPE VARCHAR(30), DAYS_PAST_DUE INT, AMOUNT_OUTSTANDING FLOAT, RESULT VARCHAR(30), AGENT_ID VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
