-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT borrower.ID AS ENTITY_ID, borrower.NAME AS ENTITY_NAME,
       borrower.REGION, borrower.CATEGORY, borrower.ALT_DATA_SCORE, borrower.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.INSTALMENT_DUE) AS INSTALMENTS_DUE,
       SUM(observation.INSTALMENT_MISSED) AS INSTALMENTS_MISSED,
       SUM(observation.AMOUNT_DUE_IDR) AS AMOUNT_DUE_IDR,
       SUM(observation.AMOUNT_PAID_IDR) AS AMOUNT_PAID_IDR,
       SUM(observation.COLLECTION_CONTACT) AS COLLECTION_CONTACTS,
       SUM(observation.PROMISE_TO_PAY) AS PROMISES_TO_PAY,
       100.0 * (SUM(observation.INSTALMENT_DUE) - SUM(observation.INSTALMENT_MISSED))
         / NULLIF(SUM(observation.INSTALMENT_DUE), 0) AS ON_TIME_RATE_PCT,
       MAX_BY(observation.DAYS_PAST_DUE, observation.EVENT_DATE) AS LATEST_DPD,
       MAX_BY(observation.OUTSTANDING_IDR, observation.EVENT_DATE) AS LATEST_OUTSTANDING_IDR,
       AVG(observation.WALLET_INFLOW_IDR) AS AVG_WALLET_INFLOW_IDR,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.LOAN_DAILY observation
JOIN RAW.BORROWERS borrower ON borrower.ID = observation.ENTITY_ID
GROUP BY borrower.ID, borrower.NAME, borrower.REGION, borrower.CATEGORY, borrower.ALT_DATA_SCORE, borrower.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(INSTALMENT_DUE) AS INSTALMENTS_DUE, SUM(INSTALMENT_MISSED) AS INSTALMENTS_MISSED,
       SUM(AMOUNT_PAID_IDR) AS AMOUNT_PAID_IDR,
       COUNT_IF(DAYS_PAST_DUE > 30) AS BORROWERS_30_DPD,
       100.0 * (SUM(INSTALMENT_DUE) - SUM(INSTALMENT_MISSED)) / NULLIF(SUM(INSTALMENT_DUE), 0) AS ON_TIME_RATE_PCT
FROM RAW.LOAN_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.PRODUCT_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH latest AS (
  SELECT ENTITY_ID, DAYS_PAST_DUE, OUTSTANDING_IDR FROM RAW.LOAN_DAILY
  WHERE EVENT_DATE = (SELECT MAX(EVENT_DATE) FROM RAW.LOAN_DAILY)
)
SELECT borrower.CATEGORY AS PRODUCT, COUNT(DISTINCT borrower.ID) AS BORROWER_COUNT,
       SUM(observation.INSTALMENT_DUE) AS INSTALMENTS_DUE,
       SUM(observation.INSTALMENT_MISSED) AS INSTALMENTS_MISSED,
       100.0 * (SUM(observation.INSTALMENT_DUE) - SUM(observation.INSTALMENT_MISSED))
         / NULLIF(SUM(observation.INSTALMENT_DUE), 0) AS ON_TIME_RATE_PCT,
       MAX(l.OUTSTANDING) AS OUTSTANDING_IDR,
       100.0 * MAX(l.PAR30_OUTSTANDING) / NULLIF(MAX(l.OUTSTANDING), 0) AS PAR30_PCT
FROM RAW.LOAN_DAILY observation
JOIN RAW.BORROWERS borrower ON borrower.ID = observation.ENTITY_ID
JOIN (SELECT b.CATEGORY, SUM(latest.OUTSTANDING_IDR) AS OUTSTANDING,
             SUM(IFF(latest.DAYS_PAST_DUE > 30, latest.OUTSTANDING_IDR, 0)) AS PAR30_OUTSTANDING
      FROM latest JOIN RAW.BORROWERS b ON b.ID = latest.ENTITY_ID GROUP BY b.CATEGORY) l
  ON l.CATEGORY = borrower.CATEGORY
GROUP BY borrower.CATEGORY;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(INSTALMENT_DUE) AS DUE, SUM(INSTALMENT_MISSED) AS MISSED,
         SUM(COLLECTION_CONTACT) AS CONTACTS, SUM(PROMISE_TO_PAY) AS PROMISES,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.LOAN_DAILY
), latest AS (
  SELECT SUM(OUTSTANDING_IDR) AS OUTSTANDING,
         SUM(IFF(DAYS_PAST_DUE > 30, OUTSTANDING_IDR, 0)) AS PAR30_OUTSTANDING
  FROM RAW.LOAN_DAILY WHERE EVENT_DATE = (SELECT MAX(EVENT_DATE) FROM RAW.LOAN_DAILY)
), book AS (SELECT COUNT(*) AS BORROWER_COUNT FROM RAW.BORROWERS),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.BORROWER_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'On-time Repayment Rate' AS TITLE,
         100.0 * (DUE - MISSED) / NULLIF(DUE, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Instalments Due', DUE, '' FROM observations
  UNION ALL SELECT 3, 'Missed Instalments', MISSED, '' FROM observations
  UNION ALL SELECT 4, 'PAR 30', 100.0 * PAR30_OUTSTANDING / NULLIF(OUTSTANDING, 0), '%' FROM latest
  UNION ALL SELECT 5, 'Outstanding (IDR bn)', OUTSTANDING / 1e9, '' FROM latest
  UNION ALL SELECT 6, 'Promise-to-Pay Rate', 100.0 * PROMISES / NULLIF(CONTACTS, 0), '%' FROM observations
  UNION ALL SELECT 7, 'Borrowers', BORROWER_COUNT, '' FROM book
  UNION ALL SELECT 8, 'Document Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 9, 'Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' AND metrics.SORT_ORDER = 5 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '999,990.0'))
                WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.PRODUCT_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
