-- Generated from generator/demo_specs/aws-indonesia-digital-economy-fintech.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-digital-economy-fintech
-- This is the schema that is actually deployed for ID_DIGITAL_ECONOMY_FINTECH.

-- Alerts fire on the top tail of NPL Ratio
-- (higher is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.91) WITHIN GROUP (ORDER BY KPI_NPL_RATIO) AS T
  FROM RAW.REPAYMENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_NPL_RATIO >= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_NPL_RATIO), 2) AS AVG_NPL_RATIO,
  ROUND(AVG(f.KPI_APPROVAL_RATE), 2) AS AVG_APPROVAL_RATE,
  ROUND(AVG(f.KPI_AVG_TICKET_SIZE), 2) AS AVG_TICKET_SIZE,
  ROUND(AVG(f.KPI_COLLECTION_RATE), 2) AS AVG_COLLECTION_RATE
FROM RAW.REPAYMENTS f
JOIN RAW.REGULATORY_REPORTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_NPL_RATIO), 2) AS AVG_NPL_RATIO,
  ROUND(AVG(f.KPI_APPROVAL_RATE), 2) AS AVG_APPROVAL_RATE,
  ROUND(AVG(f.KPI_AVG_TICKET_SIZE), 2) AS AVG_TICKET_SIZE,
  ROUND(AVG(f.KPI_COLLECTION_RATE), 2) AS AVG_COLLECTION_RATE
FROM RAW.REPAYMENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_NPL_RATIO) AS KPI_NPL_RATIO, AVG(KPI_APPROVAL_RATE) AS KPI_APPROVAL_RATE, AVG(KPI_AVG_TICKET_SIZE) AS KPI_AVG_TICKET_SIZE, AVG(KPI_COLLECTION_RATE) AS KPI_COLLECTION_RATE FROM RAW.REPAYMENTS),
     en AS (SELECT SUM(KPI_AUM_TOTAL) AS KPI_AUM_TOTAL, SUM(KPI_ACTIVE_USERS) AS KPI_ACTIVE_USERS, SUM(KPI_TRANSACTIONS_MTD) AS KPI_TRANSACTIONS_MTD FROM RAW.REGULATORY_REPORTS)
  SELECT 1 AS SORT_ORDER, 'AUM (Total)' AS TITLE, KPI_AUM_TOTAL AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_AUM_TOTAL) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Users' AS TITLE, KPI_ACTIVE_USERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_USERS) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'NPL Ratio' AS TITLE, KPI_NPL_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_NPL_RATIO), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Transactions (MTD)' AS TITLE, KPI_TRANSACTIONS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_TRANSACTIONS_MTD) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Approval Rate' AS TITLE, KPI_APPROVAL_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_APPROVAL_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Avg Ticket Size' AS TITLE, KPI_AVG_TICKET_SIZE AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_TICKET_SIZE) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Collection Rate' AS TITLE, KPI_COLLECTION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COLLECTION_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
