-- ============================================================================
-- 04_DYNAMIC_TABLES.SQL — Curated layer for Fintech Lending & Payments Analytics
-- Real aggregation logic producing analytics-ready tables
-- ============================================================================
USE DATABASE DIGITAL_FINTECH;
USE SCHEMA CURATED;

CREATE OR REPLACE DYNAMIC TABLE CURATED.LOAN_PORTFOLIO_HEALTH
  TARGET_LAG = '5 minutes'
  WAREHOUSE = FINTECH_WH
AS
SELECT
  l.PRODUCT_TYPE, l.RISK_GRADE,
  COUNT(DISTINCT l.LOAN_ID) AS TOTAL_LOANS,
  ROUND(SUM(l.LOAN_AMOUNT) / 1000000000, 2) AS TOTAL_DISBURSED_B,
  ROUND(AVG(l.INTEREST_RATE), 2) AS AVG_INTEREST_RATE,
  ROUND(SUM(CASE WHEN l.STATUS = 'DEFAULT' THEN l.LOAN_AMOUNT ELSE 0 END) / NULLIF(SUM(l.LOAN_AMOUNT), 0) * 100, 2) AS NPL_RATE,
  ROUND(SUM(CASE WHEN l.STATUS IN ('CURRENT', 'REPAID') THEN l.LOAN_AMOUNT ELSE 0 END) / NULLIF(SUM(l.LOAN_AMOUNT), 0) * 100, 1) AS PERFORMING_RATE,
  ROUND(AVG(l.TENOR_DAYS), 0) AS AVG_TENOR_DAYS,
  ROUND(AVG(b.CREDIT_SCORE), 0) AS AVG_CREDIT_SCORE
FROM RAW.LOANS l
JOIN RAW.BORROWERS b ON l.BORROWER_ID = b.BORROWER_ID
GROUP BY 1, 2;

CREATE OR REPLACE DYNAMIC TABLE CURATED.DISBURSEMENT_TREND
  TARGET_LAG = '5 minutes'
  WAREHOUSE = FINTECH_WH
AS
SELECT
  DATE_TRUNC('week', l.DISBURSEMENT_DATE) AS WEEK_START,
  l.PRODUCT_TYPE,
  COUNT(*) AS LOAN_COUNT,
  ROUND(SUM(l.LOAN_AMOUNT) / 1000000, 1) AS DISBURSED_M,
  ROUND(AVG(l.LOAN_AMOUNT), 0) AS AVG_TICKET_SIZE,
  COUNT(DISTINCT l.BORROWER_ID) AS UNIQUE_BORROWERS,
  ROUND(AVG(b.CREDIT_SCORE), 0) AS AVG_SCORE
FROM RAW.LOANS l
JOIN RAW.BORROWERS b ON l.BORROWER_ID = b.BORROWER_ID
GROUP BY 1, 2;

CREATE OR REPLACE DYNAMIC TABLE CURATED.COLLECTION_EFFECTIVENESS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = FINTECH_WH
AS
SELECT
  c.ACTION_TYPE,
  CASE WHEN c.DAYS_PAST_DUE <= 30 THEN '1-30 DPD'
       WHEN c.DAYS_PAST_DUE <= 60 THEN '31-60 DPD'
       WHEN c.DAYS_PAST_DUE <= 90 THEN '61-90 DPD'
       ELSE '90+ DPD' END AS DPD_BUCKET,
  COUNT(*) AS TOTAL_ACTIONS,
  ROUND(SUM(CASE WHEN c.RESULT = 'PROMISE_TO_PAY' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 1) AS PTP_RATE,
  ROUND(SUM(CASE WHEN c.RESULT = 'PAID' THEN c.AMOUNT_OUTSTANDING ELSE 0 END) / NULLIF(SUM(c.AMOUNT_OUTSTANDING), 0) * 100, 1) AS RECOVERY_RATE,
  ROUND(AVG(c.AMOUNT_OUTSTANDING), 0) AS AVG_OUTSTANDING
FROM RAW.COLLECTIONS c
GROUP BY 1, 2;
