-- Missed-instalment risk scoring and collection-workload forecast over the synthetic snapshot.
-- Predicts P(borrower misses an instalment in the next 14 days) and reports
-- out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.REPAYMENT_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, b.CATEGORY, b.ALT_DATA_SCORE, b.MONTHS_ON_BOOK, r.DAYS_PAST_DUE,
       AVG(r.WALLET_INFLOW_IDR) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)
         / NULLIF(AVG(r.WALLET_INFLOW_IDR) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW), 0)
         AS WALLET_7D_VS_30D,
       AVG(r.APP_SESSIONS) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS APP_SESSIONS_7D,
       SUM(r.INSTALMENT_MISSED) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS MISSED_30D,
       IFF(SUM(r.INSTALMENT_MISSED) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 14 FOLLOWING) > 0,
           'MISS', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 14 FOLLOWING) AS FUTURE_DAYS,
       SUM(r.INSTALMENT_DUE) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 14 FOLLOWING) AS FUTURE_DUE
FROM RAW.LOAN_DAILY r JOIN RAW.BORROWERS b ON b.ID = r.ENTITY_ID;

-- Time-based split: hold out the most recent 14 labelled days; train ends 14 days earlier so
-- no training label window overlaps the holdout. Borrowers already over 30 DPD are in
-- collections and are excluded from training and evaluation (their next miss is trivial).
CREATE VIEW ML.MISS_TRAIN AS
SELECT CATEGORY, ALT_DATA_SCORE, MONTHS_ON_BOOK, DAYS_PAST_DUE, WALLET_7D_VS_30D, APP_SESSIONS_7D, MISSED_30D, LABEL
FROM ML.REPAYMENT_FEATURES
WHERE FUTURE_DAYS = 14 AND FUTURE_DUE > 0 AND DAYS_PAST_DUE <= 30
  AND EVENT_DATE < DATEADD('day', -41, CURRENT_DATE());

CREATE VIEW ML.MISS_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, ALT_DATA_SCORE, MONTHS_ON_BOOK, DAYS_PAST_DUE, WALLET_7D_VS_30D,
       APP_SESSIONS_7D, MISSED_30D, LABEL
FROM ML.REPAYMENT_FEATURES
WHERE FUTURE_DAYS = 14 AND FUTURE_DUE > 0 AND DAYS_PAST_DUE <= 30
  AND EVENT_DATE >= DATEADD('day', -27, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.MISS_RISK_MODEL(
  INPUT_DATA => TABLE(ML.MISS_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.MISS_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.MISS_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'ALT_DATA_SCORE', ALT_DATA_SCORE, 'MONTHS_ON_BOOK', MONTHS_ON_BOOK,
           'DAYS_PAST_DUE', DAYS_PAST_DUE, 'WALLET_7D_VS_30D', WALLET_7D_VS_30D,
           'APP_SESSIONS_7D', APP_SESSIONS_7D, 'MISSED_30D', MISSED_30D)):probability:MISS::FLOAT AS P
  FROM ML.MISS_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'MISS', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'MISS', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'MISS', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'MISS', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per borrower (label unknown, so excluded from features).
CREATE TABLE ML.MISS_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.REPAYMENT_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.MISS_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'ALT_DATA_SCORE', ALT_DATA_SCORE, 'MONTHS_ON_BOOK', MONTHS_ON_BOOK,
           'DAYS_PAST_DUE', DAYS_PAST_DUE, 'WALLET_7D_VS_30D', WALLET_7D_VS_30D,
           'APP_SESSIONS_7D', APP_SESSIONS_7D, 'MISSED_30D', MISSED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:MISS::FLOAT, 4) AS MISS_PROB_14D,
       CASE WHEN P:probability:MISS::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:MISS::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Portfolio-wide missed-instalment forecast (14 days), for collection-team staffing.
CREATE VIEW ML.DAILY_MISSED AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(INSTALMENT_MISSED)::FLOAT AS MISSED_COUNT
FROM RAW.LOAN_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.MISSED_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_MISSED),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'MISSED_COUNT'
);

CREATE TABLE ML.MISSED_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS MISSED_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.MISSED_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
