-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Fintech Lending Analytics
-- ============================================================================
USE DATABASE FINTECH_LENDING;
USE SCHEMA ML;

-- ML.FORECAST: DEFAULT_PROBABILITY_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DEFAULT_PROBABILITY_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.VINTAGE_ANALYSIS'),
  SERIES_COLNAME => 'PRODUCT_TYPE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.DEFAULT_PROBABILITY_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.DEFAULT_PROBABILITY_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

