-- ============================================================================
-- 99_RESET.SQL — Reset Fintech Lending Analytics to clean demo state
-- ============================================================================
USE DATABASE FINTECH_LENDING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_PORTFOLIO SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_CREDIT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEFAULT SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PORTFOLIO_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.CREDIT_SCORE_FEATURES REFRESH;
ALTER DYNAMIC TABLE CURATED.VINTAGE_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CURATED.COLLECTION_STRATEGY REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM FINTECH_LENDING.RAW.BORROWERS → 3000000
-- SELECT COUNT(*) FROM FINTECH_LENDING.RAW.LOANS → 8000000
-- SELECT COUNT(*) FROM FINTECH_LENDING.RAW.REPAYMENTS → 50000000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEFAULT RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_CREDIT RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_PORTFOLIO RESUME;
